##Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be: 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
## By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

first_in_sequence = 1
second_in_sequence = 2
sum = 2
while True:
    third_in_sequence = first_in_sequence + second_in_sequence
    if third_in_sequence > 4000000:
        break
    if third_in_sequence % 2 == 0:
        sum += third_in_sequence
    # swap values
    first_in_sequence = second_in_sequence
    second_in_sequence = third_in_sequence
print(sum)